config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts
  resources :comments
  resources :likes, only: [:create, :destroy]

  devise_for :users, controllers: {
    sessions: 'user/sessions'
  }

  get 'user_posts/:user_id' => 'user/users#user_posts', as: :user_posts
  get 'profile' => 'user/users#profile', as: :user_profile
  get 'feed' => 'user/users#feed', as: :user_feed

  get 'follow_user', to: 'follows#follow', as: :follow_user
  get 'unfollow_user', to: 'follows#unfollow', as: :unfollow_user
end

app/models/user.rb
class User < ApplicationRecord
  include ImageUploader::Attachment(:image)

  before_create :set_default_avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :follows

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  validates :name, presence: true, length: { maximum: 100 }
  validates :nickname, presence: true, uniqueness: true, length: { maximum: 100 }

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  private

  def set_default_avatar
    unless self.image
      self.image = File.open("storage/default_avatar.jpeg", "rb")
    end
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def user_posts
    @user = User.find(params[:user_id])
    @posts = Post.where(user: @user).order(created_at: :desc)
  end

  def profile
    @posts = Post.where(user: current_user).order(created_at: :desc)
    @followers = current_user.followers
    @followings = current_user.following
  end

  def feed
    # @posts is only of users that current_user following
    @posts = Post.followers current_user.following
    @followings = current_user.following
  end

  private

  def user_params
    params.require(:user).permit(:user_id, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user_check(user)
    current_user.id == user.id
  end
end

app/views/user/users/_images.html.erb
<%= link_to image_tag(user.image_url,
                      style: "display: inline-block;
                              width: 100px;
                              height: 100px,
                              object-fit: contain;
                              border-radius: 50%;"),
                      user_posts_path(user) %>

app/views/user/users/_user_posts.html.erb
<% @posts.each do |post| %>
  <%= render partial: "posts/post", object: post %>
<% end %>

app/views/user/users/feed.html.erb
<h1>Subscriptions</h1>
<strong>
  <% @followings.each do |f| %>
    <% if f.image.presence %>
      <%= render partial: "user/users/images", locals: { user: f } %>
    <% end %>
    <%= link_to f.nickname, user_posts_path(f.id) %><br>
  <% end %>
</strong>
<%= render partial: "user/users/user_posts", locals: { posts: @posts } %>

app/views/user/users/profile.html.erb
<% if current_user.image.presence %>
  <p align="right">
    <%= render partial: "user/users/images", locals: { user: current_user } %>
  </p>
<% end %>
<h1 align="right"><%= "It is your page, #{current_user.name}!" %></h1>
<p align="right"><%= link_to "Edit profile", edit_user_registration_path(current_user) %></p>

<h3>Scribes: </h3>
<% @followers.each do |f| %>
  <% if f.image.presence %>
    <%= render partial: "user/users/images", locals: { user: f } %>
  <% end %>
  <%= link_to f.nickname, user_posts_path(f.id) %><br>
<% end %>

<h3>Subscriptions: </h3>
<% @followings.each do |f| %>
  <% if f.image.presence %>
    <%= render partial: "user/users/images", locals: { user: f } %>
  <% end %>
  <%= link_to f.nickname, user_posts_path(f.id) %><br>
<% end %>

<h3 align="center">Your posts </h3>

<%= render "user/users/user_posts" %>

app/views/user/users/show.html.erb
<div>
  <% if current_user.id == @user.id %>
    <h1><%= "Your posts" %></h1>
  <% else %>
    <h1><%= "#{@user.nickname} page" %></h1>
    <% if current_user_is_following(current_user.id, @user.id) %>
      <%= link_to 'Unfollow', unfollow_user_path(name: @user.name), method: :post %>
    <% else %>
      <%= link_to 'Follow', follow_user_path(name: @user.name), method: :post %>
    <% end %>
  <% end %>
</div>

<% @posts.each do |post| %>
  <%= render partial: "posts/post", object: post %>
<% end %>

app/views/user/users/user.html.erb
<% if current_user.id == @user.id %>
  <h1><%= "Your posts" %></h1><br>
<% else %>
  <h1><%= "#{@user.email} page" %></h1><br>
<% end %>

<% @posts.each do |post| %>
  <%= render post %><br>
<% end %>

app/views/user/users/user_posts.html.erb
<strong>
  <%= "It is #{@user.nickname} page!" %>
  <% if @user.image.presence %>
    <%= render partial: "user/users/images", locals: { user: @user } %>
  <% end %>
</strong>
<br>

<% unless current_user_check(@user) %>
  <% if current_user_is_following(current_user.id, @user.id) %>
    <%= link_to 'Unfollow', unfollow_user_path(nickname: @user.nickname), id: 'unfollow-button', remote: true, method: :post %>
  <% else %>
    <%= link_to 'Follow', follow_user_path(nickname: @user.nickname), id: 'follow-button', remote: true, method: :post %>
  <% end %>
<% end %>

<%= render partial: "user/users/user_posts", locals: { user: @user, posts: @posts } %>

app/views/user/users/user_profile.html.erb
<h1><%= "It is your page #{current_user.name}" %></h1>

<%= link_to "Edit profile", edit_user_registration_path(current_user) %><br>

<h3><%= "People are following you: " %></h3>
<% @user.followers.each do |f| %>
  <%= link_to f.nickname, user_posts_path(f.id) %><br>
<% end %>

<h3><%= "You are following this people: " %></h3>
<% @user.following.each do |f| %>
  <%= link_to f.nickname, user_posts_path(f.id) %><br>
<% end %>