config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts
  resources :comments
  resources :likes, only: [:create, :destroy]

  devise_for :users, controllers: {
    sessions: 'user/sessions'
  }

  get 'user_posts/:user_id' => 'user/users#user_posts', as: :user_posts
  get 'profile' => 'user/users#profile', as: :user_profile
  get 'feed' => 'user/users#feed', as: :user_feed

  get 'follow_user', to: 'follows#follow', as: :follow_user
  get 'unfollow_user', to: 'follows#unfollow', as: :unfollow_user
end

app/models/post.rb
class Post < ApplicationRecord
  include ImageUploader::Attachment(:image)

  validates :title, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  scope :followers, ->(following) { where user_id: following }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @comment = @post.comments.build
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      authorize @post
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy!
    authorize @post
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :user_id, :image, :likes)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= image_tag form.object.image_url if form.object.cached_image_data %>
    <%= form.hidden_field :image, value: form.object.cached_image_data %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post" style='padding-bottom:33px'>
  <h2>
    <%= post.title %>
  </h2>

  <p>
    <% if post.image %>
      <%= link_to image_tag(post.image_url,
                            alt: "rss feed",
                            height: 400,
                            width: 800,
                            border: 50,
                            class: "img-responsive center-block"),
                            post_path(post) %>
    <% end %>
  </p>

  <p>
    <%= link_to post.user.email, user_posts_path(post.user) %>
  </p>

  <p>
    <%= post.content %>
  </p>

  <%= render partial: "comments/comments_for_post", locals: { comments: post.comments } %>

  <%= render partial: "likes/like", locals: { post: post } %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Insta</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render partial: "posts/post", object: post %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<% if policy(@post).update? %>
  <div>
    <%= link_to "Edit this post", edit_post_path(@post) %> |
    <%= button_to "Destroy this post", @post, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete %>
  </div>
<% end %>

<%= render "comments/form", comment: @comment %>