config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts
  resources :comments
  resources :likes, only: [:create, :destroy]

  devise_for :users, controllers: {
    sessions: 'user/sessions'
  }

  get 'user_posts/:user_id' => 'user/users#user_posts', as: :user_posts
  get 'profile' => 'user/users#profile', as: :user_profile
  get 'feed' => 'user/users#feed', as: :user_feed

  get 'follow_user', to: 'follows#follow', as: :follow_user
  get 'unfollow_user', to: 'follows#unfollow', as: :unfollow_user
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <% if user_signed_in? %>
      <%= link_to "Insta", posts_path, class: "navbar-link btn btn-primary" %> |
      <%= link_to "New post", new_post_path, class: "navbar-link btn btn-primary" %> |
      <%= link_to "Feed", user_feed_path, class: "navbar-link btn btn-primary" %> |
      <%= link_to "My profile", user_profile_path(current_user), class: "navbar-link btn btn-primary" %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link btn btn-primary" %> |
      <strong align="right">Logged in as <%= current_user.email %></strong>

    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-link btn btn-primary" %> |
      <%= link_to "Login", new_user_session_path, class: "navbar-link btn btn-primary" %>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Insta</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_importmap_tags %>
</head>

<body>
<div class="container">
  <%= render 'layouts/navbar' %><br>

  <% if notice %>
    <p class="alert alert-success" style="color: green"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger" style="color: red"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>
</body>
</html>